Add payment refund handler
pickware/SwagPayPal pull request #1
Opened 2020-12-14 16:06 UTC by felixbrucker

This PR adds a payment refund handler to the paypal payment method. This allows payments created with order transaction captures to be refunded through Shopware.

2020-12-17 17:15 UTC, fixpunkt requested changes

2020-12-17 17:15 UTC, fixpunkt commented on src/Checkout/PayPalOrderTransactionCaptureService.php
> +}
Missing LF

2020-12-17 17:15 UTC, fixpunkt commented on src/PaymentsApi/Administration/PayPalPaymentController.php
> +                    break;
```suggestion
                    break;

```

2020-12-17 17:15 UTC, fixpunkt commented on src/PaymentsApi/Administration/PayPalPaymentController.php
> +                    break;
```suggestion
                    break;

```

2020-12-17 17:15 UTC, fixpunkt commented on src/Refund/PayPalRefundHandler.php
> +                    break;
```suggestion
                    break;

```

2020-12-17 17:15 UTC, fixpunkt commented on src/Refund/PayPalRefundHandler.php
> +                    break;
```suggestion
                    break;

```

2020-12-17 17:15 UTC, fixpunkt commented on src/Refund/PayPalRefundHandler.php
> +        $invoiceNumber = ''; // TODO: store in order refund transaction?
TODO

2021-01-07 10:42 UTC, fixpunkt requested changes
Re https://github.com/pickware/SwagPayPal/pull/1#discussion_r545254306 and other comments:

If formatting of `case...break` is inconsistent in the PayPal codebase anyway, I'd strongly prefer using 

```php
// do stuff
break;
```

over

```php
// do stuff

break;
```

2021-01-07 14:45 UTC, fixpunkt approved these changes
Very cool!

2021-01-11 15:00 UTC, felixbrucker commented
Closing here in favor of https://github.com/shopwareLabs/SwagPayPal/pull/14

2021-01-11 15:00 UTC, closed without merging